export const USER_LOGIN_API = "USER_LOGIN_API";
export const LOGGED_USER = "LOGGED_USER";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_CATEGORY_SAGA = "GET_ALL_CATEGORY_SAGA";
export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";
export const GET_LIST_PROJECT_SAGA = "GET_LIST_PROJECT_SAGA";
export const SHOW_DRAWER = "SHOW_DRAWER";
export const HIDE_DRAWER = "HIDE_DRAWER";
