export const CHANGE_MODAL = "CHANGE_MODAL";
export const CHANGE_ASSIGNESS = "CHANGE_ASSIGNESS";
export const REMOVE_ASSIGNEE = "REMOVE_ASSIGNEE";
export const CHANGE_TASK_ID = "CHANGE_TASK_ID";
export const CHANGE_COMMENT = "CHANGE_COMMENT";
